---
title: "Homework 5: Tomato Crop Growth Prediction"
author: "Emma Sayre, Georgia Goldsmith, Poly Shestak"
date: "May 18, 2026"
format:
  html:
    embed-resources: true
editor: visual
---

#### Load Modules

```{r}
#| label: load_modules
#| include: true
#| echo: true
#| message: false

source("fertilizer_function.R")
source("soil_health_function.R")
source("climate_function.R")
source("tomato_growth_function.R")
source("overall_program_function.R")

```

#### Generate Data & Run Program

```{r}
#| label: run-program
#| include: true
#| echo: true
#| message: false


library(truncnorm) #package for truncated normal distributions which were used to create environmental values that cannot exceed realistic min and max values
--------------------------------------------------------------------------------
# Generate example plant growth data for 20 hypothetical agricultural plots
  
plant_growth_data <- data.frame(
  plant_ID = 1:20, #unique ID for each observation
  nitrogen = rtruncnorm(20, a = 0, b = 400, mean = 70, sd = 100), #distribution of nitrogen levels in soil samples (kg/ha)
  phosphorus = rtruncnorm(20, a = 0, b = 150, mean = 20, sd = 30), #distribution of phosphorous levels in soil samples (kg/ha)
  precip = rtruncnorm(20, a = 4, b = 30, mean = 8, sd = 6), #distribution of annual precipitation across sample sites (in/yr)
  temp = rtruncnorm(20, a = 45, b = 85, mean = 70, sd = 8), #distribution of average growing temperature across sample sites (ºF)
  ph = rtruncnorm(20, a = 3.5, b = 10, mean = 6, sd = 1), #distribution of soil pH level of samples
  soil_om = rtruncnorm(20, a = 0.01, b = 0.1, mean = 0.04, sd= 0.03)) #distribution of soil organic matter concentration in samples

--------------------------------------------------------------------------------
# Calculate fertilizer suitability score
# Applies the fertilizer_score() function to each observation
# Uses nitrogen and phosphorous levels
# Higher values indicate fertilizer levels closer to optimal for plant growth
plant_growth_data$fertilizer_score <- mapply(fertilizer_score, plant_growth_data$nitrogen, plant_growth_data$phosphorus)

# Calculate climate suitability score
# Applies the climate_score() function to each observation
# Uses precipitation and temperature data
# Higher values indicate climate levels closer to optimal for plant growth
plant_growth_data$climate_score <- mapply(climate_score, plant_growth_data$precip, plant_growth_data$temp)

# Calculate soil health score
# Applies the soil_health_score() function to each observation
# Uses soil pH and soil organic matter
# Higher values indicate soil quality closer to optimal for plant growth
plant_growth_data$soil_health_score <- mapply(
  soil_health_score,
  plant_growth_data$ph,
  plant_growth_data$soil_om)

# Predict annual tomato crop growth
# Applies predict_tomato_growth() function to each observation
# Combines fertilizer, climate, and soil conditions to estimate annual tomato growth for each observation
plant_growth_data$tomato_growth <- mapply(
  predict_tomato_growth,
  plant_growth_data$nitrogen,
  plant_growth_data$phosphorus,
  plant_growth_data$precip,
  plant_growth_data$temp,
  plant_growth_data$ph,
  plant_growth_data$soil_om)

head(plant_growth_data)
```

**Test Functions**

```{r}
#| label: tests
#| include: true
#| echo: true
#| message: true

library(testthat)

# Applies tests developed for each function 

test_file("tests/test_fertilizer_function.R")
test_file("tests/test_climate_function.R")
test_file("tests/test_soil_health_function.R")
test_file("tests/test_tomato_growth_function.R")
test_file("tests/test_overall_program_function.R")

```

**Plot Tomato Plant Growth**

```{r}
#| label: plot
#| include: true
#| echo: true
#| message: false

library(ggplot2)
library(tidyverse)

# Plot predicted tomato growth at each site
plant_growth_plot <- ggplot(plant_growth_data, aes(x=plant_ID, y=tomato_growth)) +
  geom_point(color="red") +
  geom_line(color="grey") +
  geom_col(fill="pink") +
  labs(
  title = "Tomato Plant Growth in 2025",
  x = "Tomato Plant ID",
  y = "Total Growth (in)") +
  theme_bw()

plant_growth_plot
```
